### ISSUE TITLE
API Key Resource: How to create a cluster & topic?

### ISSUE THREAD

**Issue by vilmosnagy** [confluentinc/terraform-provider-confluentcloud#25] opened 2021-12-07 15:25 UTC
I have the following terraform file based on the examples:

```terraform

variable "env" {
  default = "test"
}

provider "confluentcloud" {
  api_key    = var.confluentcloud_api_key
  api_secret = var.confluentcloud_api_secret
}

variable "confluentcloud_api_key" {}
variable "confluentcloud_api_secret" {}

resource "confluentcloud_environment" "environment" {
  display_name = var.env
}

resource "confluentcloud_kafka_cluster" "basic-cluster" {
  display_name = var.env
  availability = "SINGLE_ZONE"
  cloud        = "AZURE"
  region       = var.region

  basic {

  }

  environment {
    id = confluentcloud_environment.environment.id
  }
}

resource "confluentcloud_kafka_topic" "transit-alert-trip-patches" {
  kafka_cluster      = confluentcloud_kafka_cluster.basic-cluster.id
  topic_name         = "transit-alert.trip-patches"
  partitions_count   = 4
  http_endpoint      = confluentcloud_kafka_cluster.basic-cluster.http_endpoint
  config = {
#    "cleanup.policy"    = "compact"
#    "max.message.bytes" = "12345"
#    "retention.ms"      = "67890"
  }
  credentials {
    key    = "<Kafka API Key for confluentcloud_kafka_cluster.basic-cluster>"
    secret = "<Kafka API Secret for confluentcloud_kafka_cluster.basic-cluster>"
  }
}
```

What should I put to the `confluentcloud_kafka_topic.transit-alert-trip-patches.credentials` block? With the value of the `var.confluentcloud_api_key` & `var.confluentcloud_api_secret` the `terraform apply` failes. I see no related output from the `confluentcloud_kafka_cluster.basic-cluster` block.

Is there a way to:
 - create an environment
 - create the cluster
 - and create the topics in one `terraform apply`?

Regards,

**Comment by linouk23** [comment] 2021-12-07 22:21
Thanks for raising an issue @vilmosnagy!

Reading our sample guide might [help](https://registry.terraform.io/providers/confluentinc/confluentcloud/latest/docs/guides/sample-project) to get more context.

More specifically, you for `0.2.0` TF provider version you need to follow [this section](https://registry.terraform.io/providers/confluentinc/confluentcloud/latest/docs/guides/sample-project#add-your-kafka-api-key-to-a-terraform-file). The catch is you need to use Cluster API Key instead of Cloud API Key:
```
credentials {
    key = var.kafka_api_key
    secret = var.kafka_api_secret
  }
```

Let me know if that helps!

**Comment by vilmosnagy** [comment] 2021-12-08 08:29
Thanks four your quick reply @linouk23!

If I understand you correctly, there's no way to create:
 - the cluster
 - the topics in this cluster

And there's no way to create API keys for the cluster in terraform as well.

in one terraform run. I have to:
 - create the cluster with a `terraform apply -var="should_create_the_topics_as_well=false"`
 - go to the confluent cloud website, and create an API key for the cluster on the UI
 - rerun my terraform script with `terraform apply -var="should_create_the_topics_as_well=true"`

Is that correct? That seems a bit complicated, that I can't create my _whole_ infrastructure from terraform in one go, but I have to go to the UI multiple times.

**Comment by linouk23** [comment] 2021-12-08 11:23
> Is that correct? That seems a bit complicated, that I can't create my whole infrastructure from terraform in one go, but I have to go to the UI multiple times.

That's exactly right!

That said, we are aware of these important issues and will fix in our new versions so it'll be possible to create whole infrastructure from terraform in one go without having to go to the UI at all.

**Comment by phumberdroz** [comment] 2022-02-21 21:50
Where can I keep track of this feature request?

**Comment by linouk23** [comment] 2022-02-21 22:04
@phumberdroz that's a great question, I'm not sure why I closed this issue.

The best way is probably to start watching this repository and so you're notified whenever there are any updates.

**Comment by linouk23** [comment] 2022-03-08 19:29
@itaykat it didn't, we're working on a fix that we are hoping to release toward the end of March.

**Comment by ConfluentSpencer** [comment] 2022-03-29 23:18
Duplicate of this request:
https://github.com/confluentinc/terraform-provider-confluentcloud/issues/4

**Comment by linouk23** [comment] 2022-05-04 03:54
@vilmosnagy, @itaykat we're very excited to let you know we've just published a new version of TF Provider that includes `api_key` resource among other [very exciting improvements](https://github.com/confluentinc/terraform-provider-confluent/blob/master/CHANGELOG.md): it enables fully automated provisioning of our key Kafka workflows (see the [demo](https://asciinema.org/a/491871)) with no more manual intervention and makes it our biggest and most impactful release.

The only gotcha we've renamed it from `confluentinc/confluentcloud` to `confluentinc/confluent` but we published a [migration guide](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/guides/upgrade-guide-0.7.0) so it should be fairly straightforward. The existing `confluentinc/confluentcloud` will be deprecated soon so we'd recommend switching as soon as possible.

New `confluentinc/confluent` provider also includes a lot of sample configurations so you won't need to write them from scratch. You can find them [here](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/guides/sample-project#create-resources-on-confluent-cloud-via-terraform), find a full list of changes [here](https://github.com/confluentinc/terraform-provider-confluent/blob/master/CHANGELOG.md).

**Closed by linouk23** 2022-05-04 03:54 UTC
Labels: duplicate, question, new-feature-request
