### ISSUE TITLE
data.confluentcloud_service_account.service_accounts_confluent with display name doesn't use cursor when listing...

### ISSUE THREAD

**Issue by ngapaillard** [confluentinc/terraform-provider-confluentcloud#54] opened 2022-03-15 16:42 UTC
Hi,

When using:
data "confluentcloud_service_account" "service_accounts_confluent" and display_name on an existing sa name (verified with confluent cli). The provider doesn't find the sa.
After having a look to the sources it seems the provider call the [api](https://docs.confluent.io/cloud/current/api.html#operation/listIamV2Users) that has a paginated result with 100 elements max by page... It seems in the provider the cursor of the pagination is not handled and search the service account only on the 100st service account.

**Comment by linouk23** [comment] 2022-03-15 20:14
Thanks for reporting the issue @ngapaillard and sharing the root cause!

We'll address it in our next release.

**Comment by ngapaillard** [comment] 2022-03-16 09:47
Hi do you have any idea of the due date of the next release ? In order to anticipate in our side...

**Comment by linouk23** [comment] 2022-03-16 23:14
@ngapaillard I'd expect it to happen in about 2-3 weeks but can't promise anything.

**Comment by linouk23** [comment] 2022-05-04 04:10
@ngapaillard  we're very excited to let you know we've just published a new version of TF Provider that includes a fix for this issue among other [very exciting improvements](https://github.com/confluentinc/terraform-provider-confluent/blob/master/CHANGELOG.md): it enables fully automated provisioning of our key Kafka workflows (see the [demo](https://asciinema.org/a/491871)) with no more manual intervention and makes it our biggest and most impactful release.

The only gotcha we've renamed it from `confluentinc/confluentcloud` to `confluentinc/confluent` but we published a [migration guide](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/guides/upgrade-guide-0.7.0) so it should be fairly straightforward. The existing `confluentinc/confluentcloud` will be deprecated soon so we'd recommend switching as soon as possible.

New `confluentinc/confluent` provider also includes a lot of sample configurations so you won't need to write them from scratch. You can find them [here](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/guides/sample-project#create-resources-on-confluent-cloud-via-terraform), find a full list of changes [here](https://github.com/confluentinc/terraform-provider-confluent/blob/master/CHANGELOG.md).

**Closed by linouk23** 2022-05-04 04:10 UTC
Labels: bug, in-progress
